name: MERP Research Lab
description: Multidisciplinary Electrochemical Resource Processing Lab at the University of Alberta
url: http://ren-research-lab.github.io

markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - vendor
  - "Gemfile"
  - "Gemfile.lock"
  - "deploy.sh"
  - "ghp_deploy.sh"
